title: Read between the rows
description: >- # this means to ignore newlines until "baseurl:"
  Yet-another-blog musing on data, its visualisation, and code.
  Mostly commenting on bioinformatics, sports, and health.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ideasbyjin
github_username:  ideasbyjin
instagram_username: ideasbyjin
linkedin_username: jleem
author: Jinwoo Leem
email: jinwoo.leem@gmail.com

highlighter: rouge

# Build settings
theme: minima
plugins:
  - jekyll-feed